# Generated by Django 4.1 on 2022-08-19 11:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0002_post_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Follow",
            new_name="Followed",
        ),
    ]
